{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketing-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tlsIssuer | default "selfsigned-issuer" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret | default "ticketing-tls" }}
  rules:
    - host: {{ .Values.ingress.host | default "ticket.local" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ticket-ui
                port:
                  number: {{ .Values.service.ui.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ticket-api
                port:
                  number: {{ .Values.service.api.port }}
{{- end }}
