apiVersion: v1
kind: Service
metadata:
  name: ticket-db
spec:
  selector:
    app: ticket-db
  ports:
    - protocol: TCP
      port: {{ .Values.service.db.port }}
      targetPort: 5432
  type: {{ .Values.service.db.type }}
