apiVersion: v1
kind: Service
metadata:
  name: ticket-ui
spec:
  selector:
    app: ticket-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.ui.port }}
      targetPort: 7860
  type: {{ .Values.service.ui.type }}
