apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres
spec:
  type: {{ .Values.postgres.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Chart.Name }}-postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port | default 5432 }}
      targetPort: {{ .Values.postgres.service.port | default 5432 }}
