version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ticket-db
    restart: always
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_pass
      POSTGRES_DB: bookings
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: ticket-api
    restart: always
    environment:
      DB_PATH: postgresql://ticket_user:ticket_pass@db:5432/bookings
    depends_on:
      - db
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  ui:
    build: ./ui
    container_name: ticket-ui
    restart: always
    environment:
      API_URL: http://api:5000
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "7860:7860"

volumes:
  db_data:
