apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api
spec:
  replicas: {{ if .Values.HA }}{{ .Values.replicaCount.api | default 2 }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      app: ticket-api
  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      {{- if .Values.HA }}
      affinity:
        podAntiAffinity:
          reqapiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ticket-api
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
      - name: ticket-api
        image: {{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}
        env:
        - name: API_URL
          value: {{ .Values.env.api.API_URL }}
        ports:
        - containerPort: 5000
