apiVersion: v1
kind: Service
metadata:
  name: ticket-api
spec:
  selector:
    app: ticket-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.api.port }}
      targetPort: 5000
  type: {{ .Values.service.api.type }}
