apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-ui
spec:
  replicas: {{ if .Values.HA }}{{ .Values.replicaCount.ui | default 2 }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      app: ticket-ui
  template:
    metadata:
      labels:
        app: ticket-ui
    spec:
      {{- if .Values.HA }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ticket-ui
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
      - name: ticket-ui
        image: {{ .Values.image.ui.repository }}:{{ .Values.image.ui.tag }}
        env:
        - name: API_URL
          value: {{ .Values.env.ui.API_URL }}
        ports:
        - containerPort: 7860
