image:
  repository: registry.gitlab.com/your-namespace/ticketing/api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

env:
  DB_PATH: postgresql://ticket_user:ticket_pass@ticket-db:5432/bookings
